{% set name = "coincurve" %}
{% set version = "19.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e5031ae38d0b2bc842e48c39e5a45304b28406c67da050797fda5cd50a8a79f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --use-pep517 -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cffi >=1.3.0
    - requests
    - pip
    - pkg-config
    - python
  run:
    - asn1crypto
    - {{ pin_compatible('cffi') }}
    - python

test:
  imports:
    - coincurve
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ofek/coincurve
  summary: Cross-platform Python CFFI bindings for libsecp256k1
  doc_url: https://ofek.dev/coincurve/
  description: |
    This library provides well-tested Python bindings for libsecp256k1,
    the heavily optimized C library used by Bitcoin Core for operations
    on the elliptic curve secp256k1.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE

extra:
  recipe-maintainers:
    - ofek
    - MementoRC
