{% set name = "coincurve" %}
{% set version = "19.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ofek/coincurve/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 848afd3707680dd820184c166e873e099b4ff65d413b8958f34d2020efc703e9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --use-pep517 -vvv
  script_env: PKG_CONFIG_PATH=%CONDA_PREFIX%\lib\pkgconfig  # [win]
  skip: true  # [not win or py != 310]

requirements:
  build:
    - {{ compiler('c') }}
    - libsecp256k1
  host:
    - cffi >=1.3.0
    - libsecp256k1
    - requests
    - pip
    - pkg-config
    - python
  run:
    - asn1crypto
    - {{ pin_compatible('cffi') }}
    - python

test:
  imports:
    - coincurve
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-benchmark
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/ofek/coincurve
  summary: Cross-platform Python CFFI bindings for libsecp256k1
  doc_url: https://ofek.dev/coincurve/
  description: |
    This library provides well-tested Python bindings for libsecp256k1,
    the heavily optimized C library used by Bitcoin Core for operations
    on the elliptic curve secp256k1.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE

extra:
  recipe-maintainers:
    - ofek
    - MementoRC
