{% set name = "coincurve" %}
{% set version = "20.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ofek/coincurve/archive/refs/tags/v{{ version }}.tar.gz
  sha256: be07831e54e2b6194b5f6425b3aca3e35dd23f993f57b403b5e33afef9847f5b
  patches:
    - 0001-remove-pypkgconf-win.patch
    - 0002-fix-dependency-win.patch

build:
  number: 2
  skip: True  # [win and py == 39 and python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . --use-pep517 -vvv
  script_env:
    - COINCURVE_IGNORE_SYSTEM_LIB='OFF'
    - COINCURVE_UPSTREAM_REF='__no_upstream__'

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cffi >=1.3.0  # [build_platform != target_platform]
    - cmake >=3.15
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - make  # [linux or osx]
    - pkg-config
    - python  # [build_platform != target_platform]
  host:
    - cffi >=1.3.0
    - hatchling >=1.24.2
    - libsecp256k1
    - pip
    - python
    - requests
    - scikit-build-core
    - setuptools
  run:
    - asn1crypto
    - {{ pin_compatible("cffi") }}
    - python

test:
  imports:
    - coincurve
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-benchmark
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/ofek/coincurve
  summary: Cross-platform Python CFFI bindings for libsecp256k1
  doc_url: https://ofek.dev/coincurve/
  description: |
    This library provides well-tested Python bindings for libsecp256k1,
    the heavily optimized C library used by Bitcoin Core for operations
    on the elliptic curve secp256k1.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE

extra:
  recipe-maintainers:
    - ofek
    - MementoRC
