{% set name = "coincurve" %}
{% set version = "18.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # v18.0.0 is API compatible with v19.0.0, but the conda recipe requires
  # the upgraded build process of v19.0.0.
  # The key requirement is to link with v0.2.0 of libsecp256k1, which is
  # the closest official release to the one used in v18.0.0
  url: https://github.com/ofek/coincurve/archive/refs/tags/v19.0.0.tar.gz
  sha256: 11ec706bb020be8ac268fd56ea9261b54135407ee345f953a497461d804d9db4
  patches:
    - downgrade-v19.0.0-v18.0.0.patch

build:
  number: 1
  script:  {{ PYTHON }} -m pip install . --use-pep517 -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cffi >=1.3.0
    # libsecp256k1 0.2.0 is the closest official release to the one used in v18.0.0
    - libsecp256k1 =0.2.0
    - requests
    - pip
    - pkg-config
    - python
  run:
    - asn1crypto
    - {{ pin_compatible('cffi') }}
    - python

test:
  imports:
    - coincurve
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-benchmark
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/ofek/coincurve
  summary: Cross-platform Python CFFI bindings for libsecp256k1
  doc_url: https://ofek.dev/coincurve/
  description: |
    This library provides well-tested Python bindings for libsecp256k1,
    the heavily optimized C library used by Bitcoin Core for operations
    on the elliptic curve secp256k1.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE

extra:
  recipe-maintainers:
    - ofek
    - MementoRC
